project_name: 'speedtest-go'
#dist: ./out
before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    id: speedtest-backend
    binary: speedtest-backend
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    hooks:
      post: upx -9 "{{ .Path }}"
archives:
  - id: multithread
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-multithread_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - settings.toml
      - src: web/assets
        dst: assets
        strip_parent: true
  - id: singlethread
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-singlethread_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - settings.toml
      - src: web/assets_singlethread
        dst: assets
        strip_parent: true
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: false
  sort: asc
release:
  github:
    owner: xsm1997
    name: speedtest-go
  disable: false
